name: Create magisk module

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Generate versions
      uses: HardNorth/github-version-generate@v1.4.0
      with:
        version-source: file
        version-file: module.prop
        version-file-extraction-pattern: '(?<=version=v).+'
        release-version-generate-build-metadata: true
        release-version-build-metadata-datetime: 'yyyy-MM-dd-HH-mm-ss'
    
    - name: test version
      run: |
        echo ${{ env.RELEASE_VERSION }}
        echo ${{ env.RELEASE_VERSION }}
        echo ${{ env.RELEASE_VERSION }}
        echo ${{ env.RELEASE_VERSION }}
